eclipse-tractusx/tutorial-resources

.github/workflows/run-terraform.yml, mxd/README.md, mxd/ingress.tf, mxd/main.tf, mxd/modules/connector/ingress.tf, mxd/modules/connector/nodeport.tf, mxd/modules/connector/outputs.tf, mxd/outputs.tf, mxd/postman/mxd-management-apis.json, mxd/postman/mxd-seed.json, mxd/seed_data.tf
This PR adds some very basic objects (Assets, policies, contract-defs) to both the `alice` and `bob` connector, using a tool called `newman`, packaged as Kubernetes Job. That job is declared in `mxd/seed_data.tf`.
It is important for people to be able to verify that their local setup is in fact working and to see.
the README.md has been updated accordingly.
=> feat: add seed data

mxd/keycloak.tf, mxd/main.tf, mxd/miw.tf, mxd/modules/connector/main.tf, mxd/modules/connector/nodeport.tf, mxd/modules/connector/values.yaml, mxd/outputs.tf, mxd/seed_data.tf
This PR fixes some issues we previously had with the `iss` and `aud` claims, which caused DSP requests to fail.
IN addition, the connector service now exposes a debug port (`1044`) to enable remote-debugging.
be able to execute catalog requests etc.
=> feat: fix issuer and audience for MXD

mxd/keycloak.tf, mxd/main.tf, mxd/miw.tf, mxd/modules/connector/ingress.tf, mxd/modules/connector/main.tf, mxd/modules/connector/nodeport.tf, mxd/modules/connector/variables.tf, mxd/postman/mxd-management-apis.json
This PR removes the `session_affinity` config entry, and it introduces a variable to distinguish participant ID from a "human-readable" connector name.
Also, it sets the correct `callback_address`
`session_affinity` caused problems with running MXD on windows 11/WSL2
`callback_address` is required for contract negotiations to work.
currently, both connectors use the same BPN = same Keycloak ID. It's not a problem, but it should be corrected soon.
=> feat: remove session_affinity, set callback_address

DEPENDENCIES, edc-policy-playground/src/app/components/policy-editor/policy-editor.component.css, edc-policy-playground/src/app/components/policy-editor/policy-editor.component.html, edc-policy-playground/src/app/components/policy-editor/policy-editor.component.ts, edc-policy-playground/src/app/models/policy.ts, edc-policy-playground/src/app/services/format.service.ts, edc-policy-playground/src/app/services/format/plain.ts, edc-policy-playground/src/app/services/format/prefix.ts, edc-policy-playground/src/app/services/policy.service.ts, edc-policy-playground/src/styles.css
In this PR add a select for choosing the preferred output for the policy in JSON-LD
it can: 
- plain (without usage of 
- prefix (eg. odrl: )
=> feat(playground) supports plain and prefix formats

mxd/postman/mxd-seed.json, mxd/seed_data.tf
Change the BPN to `BPNL000000000000` for seed policy and postman collection variable
=> fix: add correct BPN number to the seeded policy

mxd/miw.tf
Uses the latest MIW docker image in MXD. This is necessary, because a recent PR in Tractus-X EDC upgraded as well, and those two are incompatible.
Related: https://github.com/eclipse-tractusx/tractusx-edc/pull/731
Closes #41 
=> chore: use latest MIW image

mxd/postman/mxd-management-apis.json
update postman collection reflecting latest changes
=> chore: update postman collection reflecting latest changes

mxd/README.md, mxd/modules/connector/ingress.tf, mxd/modules/connector/outputs.tf, mxd/postman/mxd-management-apis.json, mxd/postman/mxd-seed.json
This PR enriches the EDR tutorial section:
- Updates the REAMDE for the EDR section and some words on the catalog
- Updates the terraform config for exposing the `public`  and the `proxy` endpoints of the participants dataplane.
- Updates the postman collection
=> docs: adds EDR section

mxd/3.2_MXD_tutorial2_Access_policies.md, mxd/README.md, mxd/postman/management_api_tests.json, mxd/postman/mxd-management-apis.json
- Update tutorials to demonstrate `/v3/assets` API
- Update postman collections.
Once this PRs gets merged, there will be usages / references of old `/v2/assets` API in MXD.
Closes #153 
=> doc: Update documentation / postman collections with v3 assets API

mxd/README.md
I noticed that due to the upgrade to EDC 0.4.1 in pull request https://github.com/eclipse-tractusx/tractusx-edc/pull/877, the `curl` command for EDR negotiation mentioned in the `README.md` is causing the following error.
```json
[
{
"message": "mandatory value 'https://w3id.org/edc/v0.0.1/ns/counterPartyAddress' is missing or it is blank",
"type": "ValidationFailure",
"path": "https://w3id.org/edc/v0.0.1/ns/counterPartyAddress",
"invalidValue": null
}
]
```
This pull request addresses the issue by modifying it to align with the schema of the updated EDR negotiation request.
=> fix: update EDR negotiation request

mxd/modules/connector/main.tf, mxd/modules/connector/values.yaml
- Generate private / public key pair.
- Store it in connector's vault.
- Define configs `edc.transfer.proxy.token.signer.privatekey.alias` / `edc.transfer.proxy.token.verifier.publickey.alias`
Closes #231 
=> fix: Generate private / public key pair for transfer proxy

mxd/README.md, mxd/docs/MXD Remote Deployment.md, mxd/keycloak.tf, mxd/miw.tf, mxd/variables.tf
- Changed MIW / Keycloak constant IPs as Terraform variable.
- Added a readme, how to override these variables.
Closes #275 
=> fix: Make MIW / Keycloak constant static IPs as variables

mxd/postman/mxd-seed.json
- Fixed issue with consumer data-plane (proxy) pathSegment in EDR transfer tutorial.
- Updated asset base-URL in create asset request
Closes #355 
=> fix: Fixed issue with dataplane pathsegment in EDR transfer tutorial

mxd/bdrs.tf, mxd/ingress.tf, mxd/postgres-init.tf, mxd/postman/mxd-management-apis.json, mxd/postman/mxd-seed.json, mxd/seed_data.tf
- Add BDRS Deployment via Helm Chart
- Add BPN Mapping Seed
Closes #350 
=> feat: BDRS Service Deployment and BPN Mapping Seed

.github/workflows/secrets-scan.yml
Addresses issue #428 by introducing the trufflehog secret scanning workflow, aligned with [TRG-8.03](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-03/).
=> feat: Adds Trufflehog workflow

icc-irs-challenges/ki-assistent.md
update son path leading to attributes inside job response payloa
=> chore: define json path leading to atrributes in job response

mxd/README.md, mxd/alice.tf, mxd/assets/participants.json
use the correct CatalogServer url, it was wrong before.
=> fix(deployment): use correct catalogserver url

icc-irs-challenges/ai-assistent-phase2.md
=> chore: switched to finding the submodels via the shell object

icc-irs-challenges/ai-assistent-phase1.md, icc-irs-challenges/ai-assistent-phase2.md, icc-irs-challenges/proxy.js
Optimization icc-irs-challenge
=> chore: add api key and improved phase 1 / 2

mxd/README.md
Corrected the documentation of `Minimum Tractus-X Dataspace` to have `JDK` as a prerequisite.
Fixes  #411 
=> docs: Add Java as a prerequisite for MXD

.github/workflows/stale-bot.yml
Adds a stale bot to this repo that enables marking Issues and PR's after a pre-determined period of time. Once an additional period of time passes, the Issue or PR is closed.
To avoid having unattended, i.e. that are not being actively worked on, issues or pr's for a long period of time. 
The implementation and, specially, the timelines defined for each action are in accordance with the already existing in [TractusX-EDC](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/.github/workflows/stale-bot.yml) repository. Implementing this approach aimed at keep consistency in TX and the timeframes stated are reasonable.
Timelines are:
| Type | Days Before marking as Stale | Days Before closing |
| :---         |     :---:      |          :---: |
| Issue in triage   | 32    | 14    |
| …
=> feat: Add a stale-bot to check Issues and PRs

mxd-runtimes/data-service-api/src/main/java/org/eclipse/tractusx/mxd/dataservice/DataServiceExtension.java, mxd-runtimes/data-service-api/src/main/java/org/eclipse/tractusx/mxd/dataservice/api/DataServiceApi.java, mxd-runtimes/data-service-api/src/main/java/org/eclipse/tractusx/mxd/dataservice/api/DataServiceApiController.java, mxd-runtimes/tx-issuerservice/src/main/java/org/eclipse/edc/issuerservice/demo/attestation/DemoAttestationSourceFactory.java, mxd/README.md, mxd/data-service-api.tf, mxd/postman/management_api_tests.json
This PR provide fix for the "Management API Tests" postman collection. For this data-service usability was improved(added ingress configuration and changed return type for "/v1/data" POST endpoint). Also was fixed compilation of tx-issuerservice and updated 
mxd README file with proper images from the mxd-runtimes.
Fixes #[476](https://github.com/eclipse-tractusx/tutorial-resources/issues/476)
=> fix: postman collection "Management API Tests", data-service usability and compilation of mxd-runtimes

mxd-runtimes/data-service-api/assets/postman/BackendService.postman_collection.json
This PR provide fix for the  "Backend Service" postman collection that align with the data-service API.
Fixes #516 
Please be aware that this collection improvement basing on the changes of data-service API from [PR-518](https://github.com/eclipse-tractusx/tutorial-resources/pull/518), so that PR should be merged first.
=> fix: postman collection "Backend Service"

CODEOWNERS
Update the existing codeowners file to ensure the right committers being added as reviewers
As the existing file is outdated, it needs some polishing to meet the current situation.
=> chore: Update codeowners file to reflect committer changes
