.github/workflows/verify-playground.yml
edc-policy-playground/.eslintrc.json
edc-policy-playground/package-lock.json
edc-policy-playground/package.json
edc-policy-playground/src/app/app.component.html
edc-policy-playground/src/app/app.component.spec.ts
edc-policy-playground/src/app/components/editor/editor.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-builder/constraint/atomic.constraint.component.html
edc-policy-playground/src/app/components/policy-editor/policy-builder/constraint/atomic.constraint.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-builder/constraint/constraint.list.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-builder/constraint/value.expression.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-builder/permission/dialog/constraint-dialog/constraint-dialog.component.html
edc-policy-playground/src/app/components/policy-editor/policy-builder/permission/dialog/constraint-dialog/constraint-dialog.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-builder/permission/dialog/logical-dialog/logical-dialog.component.html
edc-policy-playground/src/app/components/policy-editor/policy-builder/permission/dialog/logical-dialog/logical-dialog.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-builder/permission/permission.component.html
edc-policy-playground/src/app/components/policy-editor/policy-builder/permission/permission.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-builder/policy-builder.component.html
edc-policy-playground/src/app/components/policy-editor/policy-builder/policy-builder.component.ts
edc-policy-playground/src/app/components/policy-editor/policy-editor.component.html
edc-policy-playground/src/app/components/policy-editor/policy-editor.component.ts
edc-policy-playground/src/app/services/format.service.ts
edc-policy-playground/src/app/services/policy.service.ts

Adds workflow for checking:
- tests
- style/lint 
in PRs

feat(playground): adds workflow for PR checking

---

edc-policy-playground/src/app/models/policy.ts
edc-policy-playground/src/app/services/constraints.ts
edc-policy-playground/src/app/stores/policy.store.ts

Adds a template for the BPN Group Policy
the BPN policy was deprecated

feat: add business partner group function

---

.github/dependabot.yml

Activate dependabot on policy  playground
Closes: #7

chore(playground): add dependabot

---

.github/workflows/verify-playground.yml
DEPENDENCIES
edc-policy-playground/angular.json
edc-policy-playground/src/app/models/policy.ts
edc-policy-playground/src/app/services/format.service.ts

feat(build) add dash check

---

mxd/main.tf
mxd/miw.tf
mxd/modules/connector/main.tf
mxd/modules/connector/nodeport.tf

Use service names wherever possible instead of pod / service IP.
Closes #37 

Feature: Use service name instead of IP

---

mxd/README.md

This commit enhances documentation of section 2 of MXD Readme file by changing the place where the "cd" command is issued

Move cd command in mxd/README.md to match next commands

---

mxd/postman/management_api_tests.json
mxd/postman/mxd-seed.json
mxd/seed_data.tf

- Update mxd seed postman collection.
- Update terraform seed configuration.
- Update e2e postman collection.
Closes #156 

fix: Replace Assets v2 APIs with v3 APIs

---

mxd/3.2_MXD_tutorial2_Access_policies.md
mxd/README.md

Query Catalog Request Body update in docs (some extra fields in `querySpec`)
Closes #166

Fix: [Documentation] Update Query Catalog request in docs

---

mxd/docs/File Transfer Azure to S3.md

File Transfer Tutorial: Azure Blob to S3
Closes #126  

feat: File Transfer Tutorial: Azure Blob to S3

---

mxd/docs/File Transfer S3 to Azure.md

File Transfer Tutorial: S3 to Azure Blob
Closes #127 

feat: File Transfer Tutorial: S3 to Azure Blob

---

mxd/main.tf
mxd/modules/minio/s3bucket_job.tf

Fix: Pass MinIO Credentials to Bob Connector
Closes #221 

fix: Pass MinIO Credentials to Bob Connector

---

mxd/README.md

doc: README Update
- Postgres Container Port Update
- Some broken link fixes
Closes #214 

doc: Update Postgres Container Port in doc

---

mxd/docs/Access Policies Tutorial.md
mxd/docs/EDR Transfer Tutorial.md
mxd/docs/File Transfer Azure to Azure.md
mxd/docs/File Transfer S3 to S3.md
mxd/docs/Trudy Connector Tutorial.md
mxd/postman/management_api_tests.json

- Update Policy Definition Request Body `"@type": "odrl:Set"`
- Remove `odrl:target` at permission level while initiating negotiation.
Closes #246 

Fix: Update Policy Type to "odrl:Set"

---

mxd/docs/EDR Transfer Tutorial.md
mxd/docs/File Transfer Azure to Azure.md
mxd/docs/File Transfer S3 to S3.md
mxd/postman/mxd-management-apis.json

Doc: Update Tutorial / Postman Collection compatible with `0.6.0`.
- Add `target` field inside policy's `permission` object while initiating negotiation.
Closes #261 

doc: Tutorial update compatible with `0.6.0`

---

mxd/docs/EDR Transfer Tutorial.md

Fixed broken EDR overview link in mxd edr-api tutorial
Closes #234 

fix: Broken link in EDR tutorial

---

mxd/ingress.tf
mxd/keycloak.tf
mxd/main.tf
mxd/miw.tf
mxd/modules/connector/main.tf
mxd/modules/connector/variables.tf
mxd/modules/postgres/main.tf
mxd/modules/postgres/outputs.tf
mxd/modules/postgres/variables.tf
mxd/outputs.tf
mxd/variables.tf

- A new Postgres Terraform Module
- Separate instance for Alice, Bob connectors, MIW and Keycloak.
Closes #226 

feat: Separate Postgres server for each components

---

.github/workflows/run-terraform.yml

- Load Backend Service Docker image inside Kind Cluster
Closes #368

fix: Load Backend Service Docker Image

---

mxd/docs/Trudy Connector Tutorial.md

- Updated Trudy tutorial.
Closes: #348 

feat: Added steps for creating the 'already created' elements to Trudy Tutorial

---

mxd/backend-service/README.md
mxd/backend-service/assets/postman/BackendService.postman_collection.json
mxd/backend-service/src/main/java/org/eclipse/tractusx/mxd/backendservice/controller/ContentApiController.java
mxd/backend-service/src/main/java/org/eclipse/tractusx/mxd/backendservice/service/ContentService.java
mxd/backend-service/src/main/java/org/eclipse/tractusx/mxd/backendservice/service/ContentServiceImpl.java
mxd/backend-service/src/main/java/org/eclipse/tractusx/mxd/util/Constants.java
mxd/backend-service/src/main/java/org/eclipse/tractusx/mxd/util/RandomWordUtil.java
mxd/backend-service/src/test/java/org/eclipse/tractusx/mxd/e2e/ContentApiEndToEndTest.java
mxd/backend-service/src/test/java/org/eclipse/tractusx/mxd/testfixtures/PostgresqlEndToEndInstance.java

- Created a new endpoint for generating content with random text of a given payload size and saving it to the database.
- Updated the existing endpoint for generating random content to accept a payload size.
- Added a new E2E test for the new endpoint.
- Updated the related README and Postman collection.
Closes #376 

feat: Added new endpoint for creating synthetic test data

---

mxd/miw.tf

- Update MIW Docker image to version `0.4.0`
Closes #387 

fix: Update MIW Docker image version

---

.github/workflows/run-terraform.yml
mxd/backend-service.tf
mxd/backend-service/Dockerfile
mxd/backend-service/build.gradle.kts
mxd/backend-service/gradle/libs.versions.toml

- Add Health Check Controller
- Add Liveness / Readiness Probe for backend service
- Update Java Version in Backend Service Dockerfile
Closes #391 

fix: Update Backend Service Java Version

---

.gitignore
icc-irs-challenges/README.md
icc-irs-challenges/index.html
icc-irs-challenges/ki-guide.md
icc-irs-challenges/package-lock.json
icc-irs-challenges/package.json
icc-irs-challenges/proxy.js
icc-irs-challenges/script.js
icc-irs-challenges/style.css

This PR introduces a **Frontend Workshop Developer Guide** for the Tractus-X Days, including the example solutions for all three challenges. The solution demonstrates:
- **Challenge 1**: A basic frontend for interacting with the IRS API, including registering jobs and retrieving job details.
- **Challenge 2**: Enhanced visualization with structured JSON data and graph representation of relationships.
- **Challenge 3**: Additional details integrated into the graph for improved clarity and data representation.
The example solutions include proxy setup to handle CORS issues, API interaction, and foundational code for graph visualizations.
- Example frontend solution for participants to follow.
- Proxy setup using `http-proxy-middleware` for seamless API integration.
- Code snippets for …

Tutorial Resources for the IRS-Challenges on the third Eclipse Tractus-X Days
